### ISSUE TITLE
iSCSI protocol modifications

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/workload-fsx-ontap#14]
### Page URL

https://docs.netapp.com/us-en/workload-fsx-ontap/known-limitations.html

### Page title

Known limitations

### Summary

Hi team.
May I recommend to change this statement: The iSCSI protocol is only available for FlexGroup volumes. Since iSCSI protocol is supported with FlexVol volumes as well, that is one of the typical approaches we use around volumes/LUNs. Please review it and let me know. Thank you.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-rlithman** [comment]
Hi Javier. Thank you for your suggestion. I have two questions. 

1. The limitation is that iSCSI is only available for FlexGroup volumes not FlexVol volumes. If we say "Since iSCSI protocol is supported with FlexVol volumes", that is contrary to the limitation. Is the iSCSI protocol currently supported with FlexVol volumes? 
2. I'm not sure what you mean by "that is one of the typical approaches we use around volumes/LUNs". Can you provide more information?

**Comment by jsuarezs** [comment]
Hello.

iSCSI is both supported with FlexGroup and FlexVolume, I just pointed out the statement: "The iSCSI protocol is only available for FlexGroup volumes." is not accurate.

Regards.

**Comment by netapp-rlithman** [comment]
@jsuarezs Thank you for pointing this out. You're right. iSCSI support is only available for FlexVol volumes in BlueXP workload factory. I updated it.
